apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx-container
      imgae: rapa.iptime.org:5000/hello:latest
---
apiVersion: v1
kind: Service
metadata:
  name: pod-svc
spec:
  selector:
    app: pod-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
